### Create a new user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "fucka@aaaakuck.com",
  "password": "12345678"
}

### Find a user with id

GET http://localhost:3000/auth/2

### signout

POST http://localhost:3000/auth/signout

### Find all user with id

GET http://localhost:3000/auth?email=fucka@cuck.com

### delete user with id

DELETE http://localhost:3000/auth/1

### updateuser with id

PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "aaaa@aaaa.co"
}

### set a color

GET http://localhost:3000/auth/colors/red


### get the color

GET http://localhost:3000/auth/colors


### get the color

GET http://localhost:3000/auth/whoami


